THEMATIC_ROOMS = [
    # 0 - Abandoned Sleeping Quarters
    [
        "straw mattress",
        "bunk bed",
        "cracked bed",
        "bundle of blankets",
        "torn pillow",
        "small bedside table",
        "empty wardrobe",
    ],
    # 1 - Workshop / Smithy
    [
        "anvil",
        "workbench",
        "rusty shovel",
        "hammer",
        "crowbar",
        "broken wheel",
        "few nails scattered across the floor",
    ],
    # 2 - Storage Room
    [
        "barrel",
        "wooden crate",
        "locked chest",
        "old trunk",
        "sack of old clothes",
        "small pouch",
        "chest of drawers",
    ],
    # 3 - Ritual Chamber
    [
        "stone altar",
        "candles arranged in a circle",
        "pile of bones",
        "group of strange runes carved into the floor",
        "shattered mirror",
        "faded tapestry",
        "ceremonial dagger",
    ],
    # 4 - Alchemy Study
    [
        "bunch of dusty potion bottles",
        "cracked vial",
        "dirty mortar and pestle",
        "stained tome",
        "parchment scroll",
        "book of formulas",
        "pouch of dried herb bundles",
    ],
    # 5 - Guard Post
    [
        "weapon rack",
        "rusted spear",
        "round shield",
        "wooden chair",
        "small table",
        "discarded helmet",
        "small bag of dice carved from bone",
    ],
]

general_items = [
    # 0 - Basic Furniture
    ["wooden chair", "stool", "bench", "small table", "shelf", "dresser", "sofa"],
    # 1 - Debris and Rubble
    [
        "pile of rocks",
        "couple of loose stones",
        "bunch of rubble",
        "load of broken pottery",
        "pile of splintered beams",
        "ash pile",
        "few scattered pebbles",
    ],
    # 2 - Containers
    ["barrel", "crate", "small chest", "locked coffer", "iron-bound trunk", "canvas sack"],
    # 3 - Minor Loot
    [
        "rusted dagger",
        "pouch of coins",
        "silver ring",
        "small gem",
        "jeweled brooch",
        "tarnished copper key",
    ],
    # 4 - Wall and Decor Elements
    [
        "faded banner",
        "torn tapestry",
        "mounted torch bracket",
        "line of iron hooks on the wall",
        "cracked mirror",
        "rotting wooden beam",
    ],
]

AMBIENCES = [
    "cold and slimy",
    "bright and airy",
    "thick with damp mist",
    "heavy with the smell of mildew",
    "eerily silent",
    "echoing with distant dripping water",
    "oppressively hot",
    "filled with drifting dust motes",
    "charged with static electricity",
    "suffocatingly stale",
    "strangely tranquil",
    "buzzing faintly with unseen insects",
    "permeated by the scent of burnt herbs",
    "claustrophobic and tight",
    "wide and hollow-sounding",
    "bathed in flickering shadows",
    "tinged with metallic air",
    "unsettlingly still",
    "haunted by faint whispers",
    "vibrating softly beneath your feet",
    "carrying a low mechanical hum",
    "humid and suffocating",
    "dry as old parchment",
    "tainted with the odor of rot",
    "permeated by incense smoke",
    "unnaturally cold",
    "warped by strange acoustics",
    "filled with faint blue luminescence",
    "smelling faintly of sulfur",
    "tinged with ozone",
    "shrouded in unnatural gloom",
    "lit by a soft golden glow",
    "restless, as if watched",
]

STRUCTURAL_FEATURES = [
    "arched stone ceiling",
    "cracked marble pillars",
    "narrow arrow slits in the walls",
    "spiral staircase descending into impassible rubble",
    "raised stone dais",
    "sunken central pit",
    "iron-barred gate",
    "collapsed section of wall",
    "ornate carved doorway",
    "heavy oak door reinforced with iron",
    "stone support columns",
    "vaulted ceiling",
    "wooden rafters",
    "crumbling brickwork",
    "intricately tiled floor",
    "mosaic depicting a forgotten battle",
    "faded frescoes",
    "deep drainage trench",
    "built-in stone shelves",
    "alcove carved into the wall",
    "recessed torch holders",
    "grated floor section",
    "large circular skylight",
    "chained iron chandelier",
    "stone archway",
    "reinforced iron beams",
    "curved corridor branching outward",
    "carved gargoyle supports",
    "slanted stone floor",
    "wood-paneled walls",
    "low hanging ceiling beams",
    "narrow observation balcony",
    "iron spiral ladder",
]
THEMATIC_ITEMS = [
    # 0 - Abandoned Sleeping Quarters
    [
        "straw mattress",
        "bunk bed",
        "cracked bed",
        "bundle of blankets",
        "torn pillow",
        "small bedside table",
        "empty wardrobe",
    ],
    # Sleeping Quarters
    [
        "bunk bed",
        "straw mattress",
        "wooden wardrobe",
        "small bedside table",
        "wash basin on a stand",
        "writing desk covered in dust",
        "folding privacy screen",
    ],
    # Workshop / Smithy
    [
        "anvil",
        "large forge",
        "blackened workbench",
        "tool rack fixed to the wall",
        "bellows beside the furnace",
        "grindstone mounted on a frame",
        "metalworking table",
        "broken wheel",
    ],
    # Storage
    [
        "barrel",
        "wooden crate",
        "chest of drawers",
        "stacked wooden crates",
        "row of sealed barrels",
        "tall shelving unit",
        "large storage chest bolted to the floor",
        "hanging rack of canvas sacks",
        "supply ledger nailed to a beam",
    ],
    # Ritual Chamber
    [
        "stone altar",
        "circle of candles",
        "chalk-drawn summoning circle",
        "obsidian pedestal",
        "faded tapestry",
        "group of strange runes carved into the floor",
        "tapestry depicting occult symbols",
        "bone arrangement in ritual pattern",
        "incense brazier",
    ],
    # Alchemy Study
    [
        "alchemy workstation",
        "rack of bubbling flasks",
        "herb drying rack",
        "cracked mirror",
        "large distillation apparatus",
        "glass retort stand",
        "chalkboard covered in formulas",
    ],
    # Guard Post
    [
        "weapon rack",
        "faded banner",
        "armor stand",
        "map table",
        "wooden chair",
        "small table",
        "wooden barricade",
        "signal gong mounted on frame",
        "training dummy stuffed with straw",
    ],
    # Noble Chamber
    [
        "canopied bed",
        "ornate vanity mirror",
        "velvet chaise lounge",
        "long dining table",
        "grand bookshelf",
        "embroidered wall tapestry",
    ],
]

GENERAL_ITEMS = [
    "rusted dagger",
    "well-balanced short sword",
    "iron helmet",
    "leather gloves",
    "pair of sturdy boots",
    "silver ring",
    "gold signet ring",
    "small polished gem",
    "jeweled brooch",
    "pouch of copper coins",
    "pouch of silver coins",
    "small vial of red liquid",
    "rolled parchment scroll",
    "iron key",
    "ornate brass key",
    "bone-handled knife",
    "set of lockpicks",
    "folded cloak",
    "embroidered sash",
    "brass compass",
    "small hand mirror",
    "bundle of dried herbs",
    "sealed wax letter",
    "ivory dice set",
    "bronze medallion",
    "engraved locket",
    "cracked monocle",
    "silver chain necklace",
    "coin purse with hidden compartment",
    "small wooden idol",
    "metal flask",
    "pair of iron bracers",
    "worn leather satchel",
    "sturdy rope coil",
    "flint and steel kit",
]
