name: Commit Lint

on:
  pull_request:
  push:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v5
        with:
          firstCommit: HEAD~0  # Check only the current commit